import { Link } from "react-router-dom";
import { ArrowRight, ArrowUpRight, Truck, Wallet, ShieldCheck, RefreshCw } from "lucide-react";
import { ProductGrid } from "@/modules/product/components/ProductGrid";
import { useFeaturedProducts, useNewArrivals } from "@/modules/product/hooks/useProducts";
import { useCategories } from "@/modules/category/hooks/useCategories";
import { Reveal } from "@/shared/components/Reveal";
import { HeroSlider, type HeroSlide } from "../components/HeroSlider";
import { WhyUs } from "../components/WhyUs";
import { Testimonials } from "../components/Testimonials";
import { InstaGallery } from "../components/InstaGallery";

/* Premium hero slides — generated editorial imagery (scripts/generate_hero.py). */
const HERO_SLIDES: HeroSlide[] = [
  {
    image: "/banners/slide-men.jpg",
    eyebrow: "For Him · Premium Menswear",
    title: (
      <>
        Timeless Thobes
        <br />& <span className="font-accent text-gold-light">Jubbas</span>
      </>
    ),
    subtitle:
      "Saudi, Omani, Emirati, Moroccan and designer thobes — tailored in premium TR fabric for an effortless, regal look.",
    cta: { label: "Shop Men", to: "/shop?section=men" },
    cta2: { label: "Explore All", to: "/shop" },
  },
  {
    image: "/banners/slide-women.jpg",
    eyebrow: "For Her · Modest Elegance",
    title: (
      <>
        Graceful <span className="font-accent text-gold-light">Abayas</span>
        <br />& Burqas
      </>
    ),
    subtitle:
      "Flowing abayas with delicate gold detailing — breathable premium fabric that drapes beautifully, all day.",
    cta: { label: "Shop Women", to: "/shop?section=women" },
    cta2: { label: "New In", to: "/shop?sort=newest" },
  },
  {
    image: "/banners/slide-kids.jpg",
    eyebrow: "For Kids & Boys",
    title: (
      <>
        Little Looks,
        <br />
        Big <span className="font-accent text-gold-light">Occasions</span>
      </>
    ),
    subtitle:
      "Festive thobes, pathani suits and kurta sets for boys — the same premium quality, made child-size.",
    cta: { label: "Shop Kids", to: "/shop?section=kids" },
  },
  {
    image: "/banners/slide-pathani.jpg",
    eyebrow: "Signature · Pathani Suits",
    title: (
      <>
        The <span className="font-accent text-gold-light">Pathani</span>
        <br />
        Statement
      </>
    ),
    subtitle:
      "Knee-length kurta with a matching baggy shalwar — classic, rugged and effortlessly stylish.",
    cta: { label: "Shop Pathani", to: "/shop?section=men&category=pathani-suit" },
  },
];

/* The 8 storefront categories, in the exact order to feature on the homepage.
   Labels override the DB name for a cleaner, audience-first read; `image` points
   to the premium lifestyle cards generated by scripts/generate_categories.py. */
const CATEGORY_CARDS = [
  {
    slug: "thobe-jubba",
    label: "Men's Jubba",
    tag: "For Men",
    image: "/banners/cat-thobe-jubba.jpg",
  },
  {
    slug: "pathani-suit",
    label: "Men's Pathani Suits",
    tag: "For Men",
    image: "/banners/cat-pathani-suit.jpg",
  },
  {
    slug: "kurta-pajama",
    label: "Men's Kurta Pajama",
    tag: "For Men",
    image: "/banners/cat-kurta-pajama.jpg",
  },
  { slug: "jacket", label: "Men's Jacket", tag: "For Men", image: "/banners/cat-jacket.jpg" },
  {
    slug: "kids-thobe-jubba",
    label: "Kids & Boys Jubba",
    tag: "For Kids",
    image: "/banners/cat-kids-thobe-jubba.jpg",
  },
  {
    slug: "kids-pathani-suit",
    label: "Kids & Boys Pathani Suits",
    tag: "For Kids",
    image: "/banners/cat-kids-pathani-suit.jpg",
  },
  {
    slug: "kids-kurta-pajama",
    label: "Kids & Boys Kurta Pajama",
    tag: "For Kids",
    image: "/banners/cat-kids-kurta-pajama.jpg",
  },
  {
    slug: "abaya",
    label: "Women's Burqa / Abayas",
    tag: "For Women",
    image: "/banners/cat-abaya.jpg",
  },
];

export function HomePage() {
  const { data: featured = [], isLoading: lf } = useFeaturedProducts();
  const { data: arrivals = [], isLoading: la } = useNewArrivals();
  const { data: categories = [] } = useCategories();

  // Resolve each featured card against the live categories (for the section in
  // the link). Keep the premium lifestyle `image` from CATEGORY_CARDS; fall back
  // to the DB image only if the generated one is unavailable.
  const cards = CATEGORY_CARDS.map((c) => {
    const cat = categories.find((x) => x.slug === c.slug);
    return cat ? { ...c, image: c.image || cat.image, section: cat.section } : null;
  }).filter(Boolean) as Array<(typeof CATEGORY_CARDS)[number] & { section: string }>;

  return (
    <div className="aq-page">
      {/* ── Hero slider ─────────────────────────────────────────────────────── */}
      <HeroSlider slides={HERO_SLIDES} />

      {/* ── Trust strip — transactional trust (icons), distinct from Why-Us ──── */}
      <section className="border-b border-border bg-card">
        <div className="mx-auto grid max-w-7xl grid-cols-2 gap-y-5 px-4 py-7 md:grid-cols-4 md:px-6">
          <TrustItem icon={Truck} label="Pan-India Delivery" />
          <TrustItem icon={Wallet} label="Cash on Delivery" />
          <TrustItem icon={ShieldCheck} label="Secure Payments" />
          <TrustItem icon={RefreshCw} label="7-Day Easy Returns" />
        </div>
      </section>

      {/* ── Shop by category — the 8 storefront categories ──────────────────── */}
      <section className="mx-auto max-w-7xl px-4 py-24 md:px-6 md:py-32">
        <Reveal>
          <Heading eyebrow="Categories" title="Shop by Category" link="/shop" />
        </Reveal>
        <div className="mt-14 grid grid-cols-2 gap-3 md:grid-cols-3 md:gap-5 lg:grid-cols-4">
          {cards.map((c) => (
            <Link
              key={c.slug}
              to={`/shop?section=${c.section}&category=${c.slug}`}
              className="group relative aspect-[3/4] overflow-hidden rounded-sm bg-secondary aq-zoom ring-1 ring-transparent transition-all duration-500 hover:ring-gold/40 hover:shadow-2xl hover:shadow-navy/15"
            >
              {c.image && (
                <img
                  src={c.image}
                  alt={c.label}
                  loading="lazy"
                  className="h-full w-full object-cover"
                />
              )}
              <div className="absolute inset-0 bg-gradient-to-t from-navy via-navy/25 to-transparent transition-opacity duration-500 group-hover:from-navy/95" />
              <div className="absolute inset-x-0 bottom-0 p-5">
                <p className="text-[10px] uppercase tracking-[0.32em] text-gold-light">{c.tag}</p>
                <h3 className="mt-1.5 font-display text-lg leading-tight text-white md:text-xl">
                  {c.label}
                </h3>
                <span className="mt-2 flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-[0.18em] text-white/0 transition-all duration-300 group-hover:text-gold-light">
                  Shop Now <ArrowUpRight className="h-3.5 w-3.5" />
                </span>
              </div>
            </Link>
          ))}
        </div>
      </section>

      {/* ── Featured ────────────────────────────────────────────────────────── */}
      <section className="mx-auto max-w-7xl px-4 md:px-6">
        <Reveal>
          <Heading eyebrow="Top Picks" title="Featured Products" link="/shop" />
        </Reveal>
        <div className="mt-12">
          <ProductGrid products={featured} loading={lf} />
        </div>
      </section>

      {/* ── Why ALQAIRA — USP value props ───────────────────────────────────── */}
      <div className="mt-24 md:mt-32">
        <WhyUs />
      </div>

      {/* ── Editorial band ──────────────────────────────────────────────────── */}
      <section className="aq-grain relative my-24 overflow-hidden bg-navy text-white">
        <div className="relative mx-auto grid max-w-7xl items-center gap-12 px-4 py-24 md:px-6 lg:grid-cols-2">
          <div className="reveal">
            <div className="aq-rule" />
            <h2 className="mt-6 font-display text-4xl leading-[1.05] md:text-6xl">
              Made with <span className="font-accent text-gold-light">care</span>, in premium fabric
            </h2>
            <p className="mt-7 max-w-md text-[15px] leading-relaxed text-white/65">
              Every thobe, jubba and abaya is made from good-quality TR fabric with clean stitching
              and a comfortable fit. Simple, elegant clothing that looks great and lasts long.
            </p>
            <Link
              to="/about"
              className="mt-9 inline-flex items-center gap-2 text-sm font-semibold uppercase tracking-[0.18em] text-gold hover:gap-3"
            >
              About Us <ArrowRight className="h-4 w-4" />
            </Link>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <img
              src="/banners/cat-thobe-jubba.jpg"
              alt="Premium men's thobe"
              loading="lazy"
              className="aspect-[3/4] rounded-sm object-cover ring-1 ring-white/10"
            />
            <img
              src="/banners/cat-abaya.jpg"
              alt="Premium women's abaya"
              loading="lazy"
              className="mt-10 aspect-[3/4] rounded-[2rem] object-cover ring-1 ring-white/10"
            />
          </div>
        </div>
      </section>

      {/* ── New arrivals ────────────────────────────────────────────────────── */}
      <section className="mx-auto max-w-7xl px-4 md:px-6">
        <Reveal>
          <Heading eyebrow="Just Added" title="New Arrivals" link="/shop?sort=newest" />
        </Reveal>
        <div className="mt-12">
          <ProductGrid products={arrivals} loading={la} />
        </div>
      </section>

      {/* ── Testimonials — social proof ─────────────────────────────────────── */}
      <div className="mt-24 md:mt-32">
        <Testimonials />
      </div>

      {/* ── Instagram / lookbook gallery ────────────────────────────────────── */}
      <InstaGallery />

      {/* ── Newsletter ──────────────────────────────────────────────────────── */}
      <section className="mx-auto max-w-7xl px-4 pb-24 md:px-6">
        <Reveal className="relative overflow-hidden rounded-sm border border-gold/25 bg-secondary/60 px-6 py-16 text-center">
          <p className="eyebrow">Newsletter</p>
          <h2 className="mx-auto mt-4 max-w-xl font-display text-4xl leading-[1.05] text-foreground md:text-5xl">
            Be the first to know about new arrivals &amp;{" "}
            <span className="font-accent text-gold-dark">special</span> offers
          </h2>
          <form
            onSubmit={(e) => e.preventDefault()}
            className="mx-auto mt-8 flex max-w-md flex-col gap-3 sm:flex-row"
          >
            <input
              type="email"
              required
              placeholder="Your email address"
              className="flex-1 rounded-full border border-input bg-background px-5 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-ring"
            />
            <button type="submit" className="btn-primary">
              Subscribe
            </button>
          </form>
        </Reveal>
      </section>
    </div>
  );
}

function Heading({ eyebrow, title, link }: { eyebrow: string; title: string; link?: string }) {
  return (
    <div className="flex items-end justify-between gap-4">
      <div>
        <p className="eyebrow">{eyebrow}</p>
        <h2 className="mt-3 font-display text-4xl text-foreground md:text-5xl">{title}</h2>
        <div className="mt-4 aq-rule" />
      </div>
      {link && (
        <Link
          to={link}
          className="hidden shrink-0 items-center gap-1.5 text-sm font-medium uppercase tracking-[0.18em] text-gold-dark hover:gap-2.5 sm:flex"
        >
          View all <ArrowRight className="h-4 w-4" />
        </Link>
      )}
    </div>
  );
}

function TrustItem({
  icon: Icon,
  label,
}: {
  icon: React.ComponentType<{ className?: string }>;
  label: string;
}) {
  return (
    <div className="flex items-center justify-center gap-3">
      <Icon className="h-5 w-5 shrink-0 text-gold-dark" />
      <span className="text-[11px] font-semibold uppercase tracking-[0.18em] text-foreground/75 md:text-xs">
        {label}
      </span>
    </div>
  );
}
